### ISSUE TITLE
module install fails with error "Can't read private key - DEPMOD  3.13.0-35-generic"

### ISSUE THREAD

**Issue by mhshah** [rvido/iManager#2]
root@leed3:/home/leed/iManager-master/iManager-master# make -C /lib/modules/`uname -r`/build M=$PWD modules_install
make: Entering directory `/usr/src/linux-headers-3.13.0-35-generic'
  INSTALL /home/leed/iManager-master/iManager-master/gpio-imanager.ko
Can't read private key
  INSTALL /home/leed/iManager-master/iManager-master/i2c-imanager.ko
Can't read private key
  INSTALL /home/leed/iManager-master/iManager-master/imanager.ko
Can't read private key
  INSTALL /home/leed/iManager-master/iManager-master/imanager_bl.ko
Can't read private key
  INSTALL /home/leed/iManager-master/iManager-master/imanager_hwmon.ko
Can't read private key
  INSTALL /home/leed/iManager-master/iManager-master/imanager_wdt.ko
Can't read private key
  DEPMOD  3.13.0-35-generic
make: Leaving directory`/usr/src/linux-headers-3.13.0-35-generic'

**Comment by rvido** [comment]
Hi mhshah,
You don't have the private key that Ubuntu uses to sign kernel modules, which is why you are seeing the warning, but you should be able to safely ignore it and load those drivers you built even though they are not signed.

**Comment by mhshah** [comment]
ok.

So I ran the below command which generated the ".ko" files

make -C /lib/modules/`uname -r`/build M=$PWD

-rw-r--r-- 1 root root 10711 Dec  4 13:21 gpio-imanager.ko
-rw-r--r-- 1 root root 17491 Dec  4 13:21 i2c-imanager.ko
-rw-r--r-- 1 root root 12104 Dec  4 13:21 imanager_bl.ko
-rw-r--r-- 1 root root 42517 Dec  4 13:21 imanager_hwmon.ko
-rw-r--r-- 1 root root 50042 Dec  4 13:21 imanager.ko
-rw-r--r-- 1 root root 15623 Dec  4 13:21 imanager_wdt.ko

the below command does not install/ load these modules:
make -C /lib/modules/`uname -r`/build M=$PWD modules_install

when i lsmod, i do not see these modules. 

what is the best way to permanently load these modules?

Thanks
Milind Shah

**Comment by rvido** [comment]
The simplest way of installing the drivers into the kernel driver tree would be to using the provided make file.

#> make install

This will install all drivers into /lib/modules/your kernel release/extra/imanager/
Then, load those drivers like

#> modprobe imanager

More info can be obtained here
https://www.kernel.org/doc/Documentation/kbuild/modules.txt

**Comment by rvido** [comment]
I am closing this issue.
