### ISSUE TITLE
suggestion | mark release file with interim postfix

### ISSUE THREAD

**Issue by ghost** [rvido/iManager#5]
The following is a suggestion towards marking the `RELEASE` file version entry for specific release cycle events. If the following doesn't fit in your own release cycle process or is just not really desired, feel free to ignore this request.

---

The following suggests that the interim release value found in `RELEASE` should be appended with a `-git` postfix (ex. `v1.4.0-git`). This would allow a developer to easily confirm the non-stable variant release from just using the source. Doing this, however, requires an official release to involve two (2) commits: a release commit (removing `-git` postfix and tagging) and a kickoff cycle commit (updating new version target and re-adding postfix). Consider the following examples: [release commit](https://git.busybox.net/buildroot/commit/Makefile?id=aa6fd11feebffe16d0b0396e0e7ad421ec061272) and [kickoff cycle commit](https://git.busybox.net/buildroot/commit/Makefile?id=206ce569269a4b0b7d3ae60f9162d40b290726d8).

**Comment by rvido** [comment]
Thank you for your feedback.  I'll keep this in mind for other projects.
Closing this issue.
