### ISSUE TITLE
Question: Does GPIO driver support interrupts?

### ISSUE THREAD

**Issue by gridbox** [rvido/iManager#8]
I have successfully built and used the GPIO driver.  I noticed that the inputs do not have an `edge` file in `/sys/class/gpio/gpioXXX/`.  Based on that, I'm assuming that the GPIOs do not support interrupts.  Is that a function of the hardware or the kernel driver in gpio-imanager?

**Comment by rvido** [comment]
iManager v1 and v2 EC firmware do not support interrupts - it is a feature that has been requested many times.  This, however, will be supported in the next generation of iManager v3 firmware which will be available on SOM modules based on Intel Skylake or Kaby Lake - the EC firmware API spec has been finalized as far as I know.

Cheers,
Richard

**Comment by gridbox** [comment]
Thanks for the feedback!
