### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gentookid** [rvido/iManager#9]
I've got an IT8528 chip or at least so does it seem, it's a Razer Blade 14' 2014 system and the IT87 module reports an unknown chip 0x8520 revision a.
However upon building, installing and loading the module I get:
insmod: ERROR: could not insert module imanager-core.ko: No such device

This is on Gentoo, under 4.7.2-gentooSources.

Am I doing something wrong?

**Comment by rvido** [comment]
This basically means that the driver is not compatible with your Razor Blade.
ITE IT8516/18/28 chips on Advantech boards are embedded controllers which run custom firmware that executes a set of commands.  This command set is none standard, as it seems to me, and may not be compatible to other vendor's implementation such as Dell XPS or your Razor Blade.
I will try to make this clear in the [README](https://github.com/rvido/iManager/blob/master/README.md) file.

Please get in touch with the vendor of your Razor Blade to get more info regarding your IT8528 chip. They may not release the spec but at least tell you what this chip is been used for.
